export { createHypercube, type HypercubeOptions } from './hypercube.js';
export { createSimplex, type SimplexOptions } from './simplex.js';
export { createCrossPolytope, type CrossPolytopeOptions } from './cross-polytope.js';
export { create24Cell, type Cell24Options } from './cell24.js';
export { create600Cell, type Cell600Options } from './cell600.js';
export { create120Cell, create120CellCompiled, type Cell120Options } from './cell120.js';
export { createDuoprism, type DuoprismOptions } from './duoprism.js';
export { createCliffordCurve, type CliffordCurveOptions } from './clifford-curve.js';
export { createSnub24Cell, createSnub24CellCompiled, type Snub24CellOptions } from './snub24.js';
export { createGrandAntiprism, createGrandAntiprismCompiled, type GrandAntiprismOptions } from './grand-antiprism.js';
export { createHopfFiber, type HopfFiberOptions } from './hopf.js';
