import { buildRagged, type FaceLattice } from '../geometry/face-lattice.js';
import { compileFaceLattice, type CompiledPolytope } from '../geometry/compile-lattice.js';
import {
  enumerateCoxeterAction,
  reflectDistances,
  wythoffSeed,
  type CoxeterAction
} from './action.js';
import type { CoxeterDiagram } from './diagram.js';
import type { ExactValue } from './exact.js';
import { CoxeterRealization } from './realization.js';

export interface WythoffOptions {
  /** Scale so the circumradius equals this. Default: leave unscaled. */
  radius?: number;
}

type Mark = 0 | 1 | 2;

interface Decoration {
  readonly marks: Mark[];
  /** Number of marks equal to 2 = intrinsic face dimension. */
  readonly rank: number;
  /** Stabilizer generators: every node whose mark is not 1. */
  readonly stabilizer: number[];
  /** Transitions: star(this, node) = decorations[upper]. */
  readonly upper: Array<{ node: number; type: number }>;
}

/**
 * Whitehead's star operation on a decorated diagram: mark the selected
 * 1-node as 2 and wake its diagram-adjacent 0-neighbours to 1. After k
 * stars the 2-nodes generate a representative k-face containing the
 * seed; the face's stabilizer is generated by all non-1 nodes.
 */
function star(marks: readonly Mark[], selected: number, diagram: CoxeterDiagram): Mark[] {
  if (marks[selected] !== 1) throw new Error('star: node must be marked 1');
  const out = marks.slice();
  out[selected] = 2;
  for (let j = 0; j < marks.length; j++) {
    if (j !== selected && diagram.matrix[selected]![j]! > 2 && out[j] === 0) out[j] = 1;
  }
  return out;
}

/** BFS the DAG of decorations reachable from the initial ring marks. */
function enumerateDecorations(diagram: CoxeterDiagram, rings: readonly boolean[]): Decoration[] {
  const initial = rings.map((r) => (r ? 1 : 0)) as Mark[];
  const decorations: Decoration[] = [];
  const ids = new Map<string, number>();
  const intern = (marks: Mark[]): number => {
    const key = marks.join('');
    let id = ids.get(key);
    if (id === undefined) {
      id = decorations.length;
      ids.set(key, id);
      decorations.push({
        marks,
        rank: marks.filter((m) => m === 2).length,
        stabilizer: marks.flatMap((m, i) => (m !== 1 ? [i] : [])),
        upper: []
      });
    }
    return id;
  };
  intern(initial);
  for (let head = 0; head < decorations.length; head++) {
    const d = decorations[head]!;
    if (d.rank >= diagram.rank - 1) continue; // rank-4 face is the polytope itself
    for (let node = 0; node < diagram.rank; node++) {
      if (d.marks[node] !== 1) continue;
      d.upper.push({ node, type: intern(star(d.marks, node, diagram)) });
    }
  }
  return decorations;
}

interface CosetPartition {
  readonly faceOfChamber: Uint32Array;
  readonly representative: Uint32Array;
}

/**
 * Partitions the group into left cosets g·W_S of the subgroup generated
 * by `generators`, by BFS closure under **right** multiplication. Each
 * coset is one translated face.
 */
function partitionCosets(action: CoxeterAction, generators: readonly number[]): CosetPartition {
  const faceOf = new Uint32Array(action.order).fill(0xffffffff);
  const representatives: number[] = [];
  const queue = new Uint32Array(action.order);
  let faceId = 0;
  for (let start = 0; start < action.order; start++) {
    if (faceOf[start] !== 0xffffffff) continue;
    representatives.push(start);
    let read = 0;
    let write = 0;
    queue[write++] = start;
    faceOf[start] = faceId;
    while (read < write) {
      const g = queue[read++]!;
      for (const s of generators) {
        const h = action.rightMultiply[g * action.rank + s]!;
        if (faceOf[h] === 0xffffffff) {
          faceOf[h] = faceId;
          queue[write++] = h;
        }
      }
    }
    faceId++;
  }
  return { faceOfChamber: faceOf, representative: Uint32Array.from(representatives) };
}

/** Canonical cycle: start at the smallest vertex, lesser direction first. */
function canonicalCycle(cycle: number[]): number[] {
  let start = 0;
  for (let i = 1; i < cycle.length; i++) if (cycle[i]! < cycle[start]!) start = i;
  const n = cycle.length;
  const forward: number[] = [];
  const backward: number[] = [];
  for (let k = 0; k < n; k++) {
    forward.push(cycle[(start + k) % n]!);
    backward.push(cycle[(start - k + n) % n]!);
  }
  for (let k = 1; k < n; k++) {
    if (forward[k]! !== backward[k]!) return forward[k]! < backward[k]! ? forward : backward;
  }
  return forward;
}

/**
 * The Wythoff construction: a uniform polytope from a ringed Coxeter
 * diagram, as an exact face lattice compiled to a render-ready complex.
 *
 * Everything topological is integer/group computation — coset
 * partitions of the chamber action give the faces, shared chambers give
 * the cover relations, and polygon cycles come from walking exact edge
 * incidence (no angle sorting anywhere). Geometry enters only at the
 * end: one exact-to-Float64 conversion of each vertex's mirror-distance
 * tuple.
 */
export function createWythoffPolytope(
  diagram: CoxeterDiagram,
  rings: readonly boolean[],
  options: WythoffOptions = {}
): CompiledPolytope {
  if (diagram.rank !== 4) {
    throw new Error(`createWythoffPolytope: rank-4 diagrams only, got rank ${diagram.rank}`);
  }
  const action = enumerateCoxeterAction(diagram);
  const seed = wythoffSeed(diagram, rings);
  const decorations = enumerateDecorations(diagram, rings);

  // Exact point tuple of every chamber: tuple[g] = g(seed), built along
  // the BFS tree (left multiplication = simple-mirror reflection).
  const tuples: ExactValue[][] = new Array(action.order);
  tuples[0] = seed;
  for (let g = 1; g < action.order; g++) {
    tuples[g] = reflectDistances(
      tuples[action.parent[g]!]!,
      action.parentGenerator[g]!,
      diagram.twoGram,
      diagram.ring
    );
  }

  // One coset partition per decoration; the initial decoration's cosets
  // are the vertices.
  const partitions = decorations.map((d) => partitionCosets(action, d.stabilizer));
  const vertexOfChamber = partitions[0]!.faceOfChamber;
  const vertexCount = partitions[0]!.representative.length;

  // Cross-validate cosets against exact geometry: chambers in one vertex
  // coset must carry identical seed tuples, distinct cosets distinct ones.
  const tupleKeyOfVertex = new Map<string, number>();
  for (let g = 0; g < action.order; g++) {
    const key = diagram.ring.keyTuple(tuples[g]!);
    const v = vertexOfChamber[g]!;
    const seen = tupleKeyOfVertex.get(key);
    if (seen === undefined) tupleKeyOfVertex.set(key, v);
    else if (seen !== v) throw new Error(`${diagram.id}: vertex coset/tuple mismatch`);
  }
  if (tupleKeyOfVertex.size !== vertexCount) {
    throw new Error(`${diagram.id}: ${tupleKeyOfVertex.size} tuples for ${vertexCount} vertices`);
  }

  // Vertex sets of every face of every decoration, then global faces
  // per rank with canonical vertex-set dedup across decoration types.
  const globalIdByKey = new Map<string, number>();
  const facesByRank: Array<Array<{ vertices: number[]; typeId: number }>> = [[], [], [], []];
  // faceGlobal[d][localFace] = global ID within its rank layer.
  const faceGlobal: Int32Array[] = [];
  decorations.forEach((d, di) => {
    const partition = partitions[di]!;
    const sets: Array<Set<number>> = Array.from(
      { length: partition.representative.length },
      () => new Set()
    );
    for (let g = 0; g < action.order; g++) {
      sets[partition.faceOfChamber[g]!]!.add(vertexOfChamber[g]!);
    }
    const globals = new Int32Array(sets.length);
    sets.forEach((set, local) => {
      const vertices = [...set].sort((a, b) => a - b);
      const key = `${d.rank}:${vertices.join(',')}`;
      let id = globalIdByKey.get(key);
      if (id === undefined) {
        id = facesByRank[d.rank]!.length;
        globalIdByKey.set(key, id);
        facesByRank[d.rank]!.push({ vertices, typeId: di });
      }
      globals[local] = id;
    });
    faceGlobal.push(globals);
  });

  const edges = facesByRank[1]!;
  for (const e of edges) {
    if (e.vertices.length !== 2) {
      throw new Error(`${diagram.id}: edge with ${e.vertices.length} vertices`);
    }
  }

  // Cover relations from shared chambers: for each star transition the
  // same chamber g identifies an incident (lower, upper) face pair.
  const covers: Array<Set<number>> = [new Set(), new Set(), new Set()]; // rank k→k+1, k=0 unused
  decorations.forEach((d, di) => {
    for (const { type: upperType } of d.upper) {
      const lowerGlobal = faceGlobal[di]!;
      const upperGlobal = faceGlobal[upperType]!;
      const lowerOf = partitions[di]!.faceOfChamber;
      const upperOf = partitions[upperType]!.faceOfChamber;
      const bucket = covers[d.rank]!;
      for (let g = 0; g < action.order; g++) {
        bucket.add(lowerGlobal[lowerOf[g]!]! * 0x100000 + upperGlobal[upperOf[g]!]!);
      }
    }
  });

  // boundary maps: upper face → its lower faces.
  const boundaryOf = (rank: 2 | 3): number[][] => {
    const upperCount = facesByRank[rank]!.length;
    const result: number[][] = Array.from({ length: upperCount }, () => []);
    for (const packed of covers[rank - 1]!) {
      const lower = Math.floor(packed / 0x100000);
      const upper = packed % 0x100000;
      result[upper]!.push(lower);
    }
    return result;
  };
  const faceEdges = boundaryOf(2);
  const cellFaces = boundaryOf(3);

  // Cyclic polygon order, purely combinatorially: walk the degree-2
  // adjacency induced by the face's boundary edges.
  const polygons = facesByRank[2]!.map((face, f) => {
    const adjacency = new Map<number, number[]>();
    const link = (a: number, b: number): void => {
      let list = adjacency.get(a);
      if (!list) adjacency.set(a, (list = []));
      list.push(b);
    };
    for (const e of faceEdges[f]!) {
      const [a, b] = edges[e]!.vertices as [number, number];
      link(a, b);
      link(b, a);
    }
    if (adjacency.size !== face.vertices.length) {
      throw new Error(`${diagram.id}: polygon ${f} edge/vertex mismatch`);
    }
    const cycle: number[] = [face.vertices[0]!];
    let previous = -1;
    while (cycle.length < face.vertices.length) {
      const here = cycle[cycle.length - 1]!;
      const neighbors = adjacency.get(here)!;
      if (neighbors.length !== 2) {
        throw new Error(`${diagram.id}: polygon ${f} vertex of degree ${neighbors.length}`);
      }
      const next = neighbors[0] === previous ? neighbors[1]! : neighbors[0]!;
      previous = here;
      cycle.push(next);
    }
    return canonicalCycle(cycle);
  });

  // Realize the vertices: one exact→Float64 conversion per vertex, then
  // the optional circumradius normalization.
  const realization = new CoxeterRealization(diagram);
  const positions = new Float64Array(vertexCount * 4);
  const d = new Array<number>(4);
  const x = new Float64Array(4);
  for (let v = 0; v < vertexCount; v++) {
    const tuple = tuples[partitions[0]!.representative[v]!]!;
    for (let i = 0; i < 4; i++) d[i] = diagram.ring.toNumber(tuple[i]!);
    realization.realizeDistances(d, x);
    positions.set(x, v * 4);
  }
  if (options.radius !== undefined) {
    const r0 = Math.hypot(positions[0]!, positions[1]!, positions[2]!, positions[3]!);
    const scale = options.radius / r0;
    for (let i = 0; i < positions.length; i++) positions[i]! *= scale;
  }

  const lattice: FaceLattice = {
    rank: 4,
    vertexCount,
    layers: [
      undefined,
      { vertices: buildRagged(edges.map((e) => e.vertices)), typeId: Uint16Array.from(edges.map((e) => e.typeId)) },
      { vertices: buildRagged(polygons), typeId: Uint16Array.from(facesByRank[2]!.map((f) => f.typeId)) },
      { vertices: buildRagged(facesByRank[3]!.map((c) => c.vertices)), typeId: Uint16Array.from(facesByRank[3]!.map((c) => c.typeId)) }
    ],
    boundary: [undefined, undefined, buildRagged(faceEdges), buildRagged(cellFaces)]
  };

  return compileFaceLattice(lattice, positions);
}
